apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minio" 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-local-claim
  namespace: minio-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi