apiVersion: v1
kind: Namespace
metadata:
  name: minio-storage


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minio" 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-local-claim
  namespace: minio-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  

    
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-storage
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30091
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30092


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-storage
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberrypi 
      containers:
      - name: minio
        # 使用官方镜像，ARM64支持完美
        image: minio/minio:latest 
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "password123"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: "/data"
      volumes:
      - name: storage
        persistentVolumeClaim:
          # 直接使用我们之前修好的那个PVC
          claimName: minio-local-claim 

