apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-storage
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        # 确保跑在那个有数据的树莓派节点上
        kubernetes.io/hostname: raspberrypi 
      containers:
      - name: minio
        # 使用官方镜像，ARM64支持完美
        image: minio/minio:latest 
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "password123"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: "/data"
      volumes:
      - name: storage
        persistentVolumeClaim:
          # 直接使用我们之前修好的那个PVC
          claimName: minio-local-claim 

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-storage
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30091
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30092